### ISSUE TITLE
Please update ProvidedTypes.fs for Mono 5.0 

### ISSUE THREAD

**Issue by dsyme** [kellerd/TicTacToeProvider#3]
Please update to use the latest version of ProvidedTypes.fs, as described in fsprojects/FSharp.TypeProviders.StarterPack#121

Many thanks

**Comment by kellerd** [comment]
Updated, though not one of the most important of projects, thanks for caring.  Now even mono users can play tic-tac-toe in their IDE

**Comment by dsyme** [comment]
Yep :)

**Comment by dsyme** [comment]
(github code search turns up all sort of things! :) )
